name: goodsciproj_env
dependencies:
    - python>=3.9
    - pytest
    - sphinx<=7.4 # TODO(CB): update sphinx allowed version (after they fix their bug)
    - conda-forge::doxygen>=1.10.0
    - pip
    - pip:
      - -r requirements.txt
